call plug#begin('~/.nvim/plugged')

Plug 'scrooloose/nerdtree'
Plug 'kien/ctrlp.vim'
Plug 'tomtom/tcomment_vim'
Plug 'mileszs/ack.vim'
Plug 'terryma/vim-multiple-cursors'
Plug 'itchyny/lightline.vim'
Plug 'altercation/vim-colors-solarized'
Plug 'fatih/vim-go'
Plug 'tpope/vim-surround'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'zchee/deoplete-go', { 'do': 'make'}

call plug#end()

" disable mouse (set to command-line mode)
set mouse=c 

" Use ag instead of ack
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

" https://github.com/Shougo/deoplete.nvim/blob/master/doc%2Fdeoplete.txt
call deoplete#enable()

" Enable Solarized Scheme
let $NVIM_TUI_ENABLE_TRUE_COLOR=1 " unclear if this is really needed?
syntax enable
set background=dark
colorscheme solarized

set number

let g:lightline = {
\ 'colorscheme': 'solarized',
\ }

let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

" let g:go_play_open_browser = 0
"
